name: alignpose_gpu
channels:
  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
dependencies:
  - python=3.9
  - omegaconf
  - fvcore
  - iopath
  - conda-forge:faiss-gpu=1.8.0 # GPU
  - scipy=1.13.0
  - kiwisolver=1.3.1
  - matplotlib=3.8.4
  - pillow=10.3.0
  - pip=24.0
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - numpy==1.26.4
    - vispy==0.12.1
    - torch==2.8.0+cu126 # GPU
    - torchvision==0.23.0+cu126 # GPU
    - torchinfo
    - torchmetrics>=1.0.0
    - cython==3.0.10
    - xformers
    - manifold3d
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu12>=24.02 # GPU
    - kornia==0.7.2
    - pypng==0.20220715.0
    - triangle==20200424
    - glumpy==1.2.1
    - pycocotools==2.0
    - scikit-learn==1.5.0
    - scikit-image==0.22.0
    - imageio==2.34.1
    - pyopengl==3.1.0
    - pyopengl-accelerate
    - pyglet==2.0.15
    - pytz==2024.1
    - pyrender==0.1.45
    - webdataset==0.2.86
    - opencv-python==4.5.5.62
    - transformers
    - huggingface-hub
